---
workers:
    - {name: csv-to-task, class: drm.taskworker.workers.CSVtoTaskWorker, threads: 2, code: "file://${cwd}/target/examples-0.2.0-SNAPSHOT.jar"}
    - {name: template-to-xml, class: drm.taskworker.workers.TemplateWorker, threads: 2, code: "file://${cwd}/target/examples-0.2.0-SNAPSHOT.jar"}
    - {name: xsl-fo-render, class: drm.taskworker.workers.XslFoRenderWorker, threads: 2, code: "file://${cwd}/target/examples-0.2.0-SNAPSHOT.jar"}
    - {name: zip-files, class: drm.taskworker.workers.ZipWorker, threads: 2, code: "file://${cwd}/target/examples-0.2.0-SNAPSHOT.jar"}
    - {name: join, class: drm.taskworker.workers.JoinWorker, threads: 2, code: "file://${cwd}/target/examples-0.2.0-SNAPSHOT.jar"}
    - {name: archive, class: drm.taskworker.workers.ArchiveWorker, threads: 2, code: "file://${cwd}/target/examples-0.2.0-SNAPSHOT.jar"}

workflows:
    invoices:
        steps:
            csv-to-task: {next: template-to-xml}
            template-to-xml: {next: xsl-fo-render}
            xsl-fo-render: {next: join}
            join: {next: zip-files}
            zip-files: {next: archive}
        start: csv-to-task
        end: archive

scheduler:
    class: drm.taskworker.schedule.FairShare
    workers:
        - csv-to-task
        - template-to-xml
        - xsl-fo-render
        - join
        - zip-files
        - archive
